#!/bin/bash
# Remove last docker image and create new

docker-compose down
sudo docker rmi -f polc/tlog16angular
npm run build
sudo docker build --no-cache -t polc/tlog16angular .
docker-compose up -d
